# Prettier – cấu hình thống nhất cho toàn bộ dự án
# Mọi thành viên dùng chung file này, KHÔNG override

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
